### ISSUE TITLE
새로운 멤버 - 강혜란 

### ISSUE THREAD

**Issue by jaelyung** [jaelyung/Lets-chat#17]
- MySQL 설치, MySQL workbench 스키마 testdb 생성, user 생성(id: chat / pw: chat)
- 스키마 생성 참고 https://goddaehee.tistory.com/278

**Comment by hyeran930331** [comment]
2021.01.04 MySQL 설치, MySQL workbench 스키마 testdb 생성, user 생성(id: chat / pw: chat) 완료
